apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dns-web-nextauth
  namespace: web
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: dns-web-nextauth
    creationPolicy: Owner
  data:
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: secret/data/k8s/dns-web
        property: nextauth-secret
